### ISSUE TITLE
issue importing 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zhihu/Matisse#81] opened 2017-05-27 14:15 UTC
I get this:

```
Unable to load class 'org.gradle.api.internal.component.Usage'. Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.) Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem. Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

![image](https://cloud.githubusercontent.com/assets/5357526/26522033/196508b6-4300-11e7-8cab-ba08d54825ce.png)

**Comment by gejiaheng** [comment] 2017-05-27 22:30
Have you tried what the log told? Any updates?

**Comment by AndroidDeveloperLB** [comment] 2017-05-27 22:49
Yes I tried both. Weird thing is that other repos also have this issue, while others work fine.

**Comment by gejiaheng** [comment] 2017-06-22 06:31
Em, it's been a long time. Have you resolved it? I assume you probably updated Android Studio.

**Comment by gejiaheng** [comment] 2017-06-22 06:41
I'll close this issue for now. You can reopen it if the problem is still there.

**Closed by gejiaheng** 2017-06-22 06:41 UTC

**Comment by AndroidDeveloperLB** [comment] 2017-06-22 06:44
@gejiaheng Now it works. Yes. 
But, what does it do?
It has 2 buttons, to select photos and hit "apply", but it doesn't do anything...
Is it supposed to do anything?

**Comment by gejiaheng** [comment] 2017-06-22 06:53
@AndroidDeveloperLB 
You can refer to https://github.com/zhihu/Matisse/issues/64. It may give you an answer.
And check out the project's wiki: https://github.com/zhihu/Matisse/wiki

And what is drag-to-multi-select? I only know a feature which is drag to open a menu in the dropdown list, and Matisse supports it.

**Comment by AndroidDeveloperLB** [comment] 2017-06-22 07:01
Sorry I don't get it.

About the feature I wrote, here:
https://stackoverflow.com/q/41199611/878126
Taken from:
https://material.io/guidelines/patterns/selection.html#selection-usage
Example library:
https://github.com/afollestad/drag-select-recyclerview

**Comment by gejiaheng** [comment] 2017-06-22 07:17
Oh, I get it. It's a nice feature. You can contribute if you want to.

**Comment by AndroidDeveloperLB** [comment] 2017-06-22 07:26
Still not sure what this library sample do
